 platform :ios, '13.5'


target 'Runner' do
  use_frameworks! :linkage => :static
  
  pod 'VBotPhoneSDK', :podspec => 'https://github.com/quocdat1804/VBotSIP/releases/download/1.0.0/VBotPhoneSDK.podspec'
  pod 'VBotSIP', :podspec => 'https://github.com/quocdat1804/VBotSIP/releases/download/1.0.0/VBotSIP.podspec'
  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

